// Yeh tumhari saari images ka data hai - direct load, no cache
export const IMAGES = [
  {
    "public_id": "Sunset_Beach",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772821278/IMG-20260306-WA0025_cozmpa.jpg",
    "title": "Sunset Beach",
    "category": "Medium-Acrylic",
    "price": 2999,
    "originalPrice": 3549,
    "sku": "SKU# ",
    "year": 2024,
    "size": "08 x 10 inches",
    "description": "Acrylic On Stretched Canvas",
    "medium": "Acrylic on Canvas",
    "isSold": true
  },
  {
    "public_id": "Snowfall",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772821244/IMG-20260306-WA0024_koguvj.jpg",
    "title": "Snowfall",
    "category": "Medium-Acrylic",
    "price": 2999,
    "originalPrice": 3549,
    "sku": "SKU# ",
    "year": 2024,
    "size": "08 x 10 inches",
    "description": "Acrylic On Stretched Canvas",
    "medium": "Acrylic",
    "isSold": true
  },
  {
    "public_id": "Sunset",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772821121/IMG-20260306-WA0023_secxez.jpg",
    "title": "Sunset",
    "category": "Medium-Acrylic",
    "price": 2999,
    "originalPrice": 3549,
    "sku": "SKU# ",
    "year": 2024,
    "size": "12 x 12 inches",
    "description": "Acrylic On Stretched Canvas",
    "medium": "Acrylic on Canvas",
    "isSold": true
  },
  {
    "public_id": "Sailboat",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772818820/IMG-20260303-WA0013_wwxs1y.jpg",
    "title": "Sailboat",
    "category": "Medium-Acrylic",
    "price": 2999,
    "originalPrice": 3549,
    "sku": "SKU# ",
    "year": 2024,
    "size": "18 x 18 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas",
    "isSold": false
  },
  {
    "public_id": "A0006_Bright_Snowy_Autumn_Landscape_qstoj7",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--3KRMZFnB--/c_limit,w_1200/q_auto/f_auto/A0006_Bright_Snowy_Autumn_Landscape_qstoj7?_a=BAMAOGUs0",
    "title": "Bright Snowy Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0006",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0007_Cabin_in_a_Snowy_Landscape_ovfx9h",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--SRS9EUmY--/c_limit,w_1200/q_auto/f_auto/A0007_Cabin_in_a_Snowy_Landscape_ovfx9h?_a=BAMAOGUs0",
    "title": "Cabin in a Snowy Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0007",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0008_Wooden_Bridge_in_a_Snowy_Landscape_m2snny",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--k-IcpIvl--/c_limit,w_1200/q_auto/f_auto/A0008_Wooden_Bridge_in_a_Snowy_Landscape_m2snny?_a=BAMAOGUs0",
    "title": "Wooden Bridge in a Snowy Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0008",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0009_Snowy_Night_Landscape_nn0myi",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--vUOjCpdM--/c_limit,w_1200/q_auto/f_auto/A0009_Snowy_Night_Landscape_nn0myi?_a=BAMAOGUs0",
    "title": "Snowy Night Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0009",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0010_Log_Bridge_Autumn_Landscape_owgs30",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Q52v9gul--/c_limit,w_1200/q_auto/f_auto/A0010_Log_Bridge_Autumn_Landscape_owgs30?_a=BAMAOGUs0",
    "title": "Log Bridge Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0010",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0011_Full_Moon_Autumn_Landscape_prpnub",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--X_pZOnJW--/c_limit,w_1200/q_auto/f_auto/A0011_Full_Moon_Autumn_Landscape_prpnub?_a=BAMAOGUs0",
    "title": "Full Moon Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0011",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0012_Beautiful_Mountain_Landscape_kvvsxo",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Hvvbzzd1--/c_limit,w_1200/q_auto/f_auto/A0012_Beautiful_Mountain_Landscape_kvvsxo?_a=BAMAOGUs0",
    "title": "Beautiful Mountain Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0012",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0013_Beach_Landscape_nt4gcn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--r5ku7INw--/c_limit,w_1200/q_auto/f_auto/A0013_Beach_Landscape_nt4gcn?_a=BAMAOGUs0",
    "title": "Beach Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0013",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0014_Road_along_the_Humongous_Trees_mpojk4",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--kwMqXIp3--/c_limit,w_1200/q_auto/f_auto/A0014_Road_along_the_Humongous_Trees_mpojk4?_a=BAMAOGUs0",
    "title": "Road along the Humongous Trees",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0014",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0015_Thatched_House_Landscape_estxhy",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--oEdzTajP--/c_limit,w_1200/q_auto/f_auto/A0015_Thatched_House_Landscape_estxhy?_a=BAMAOGUs0",
    "title": "Thatched House Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0015",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0016_A_Girl_in_a_Rainy_Night_l9qvai",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--i4f8R2sZ--/c_limit,w_1200/q_auto/f_auto/A0016_A_Girl_in_a_Rainy_Night_l9qvai?_a=BAMAOGUs0",
    "title": "A Girl in a Rainy Night",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0016",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0017_Lighthouse_Along_the_Bay_dwkzhe",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--5CTWppkf--/c_limit,w_1200/q_auto/f_auto/A0017_Lighthouse_Along_the_Bay_dwkzhe?_a=BAMAOGUs0",
    "title": "Lighthouse Along the Bay",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0017",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0018_Bright_Green_Landscape_with_a_Beautiful_Swan_x0vpns",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--2BczoTRw--/c_limit,w_1200/q_auto/f_auto/A0018_Bright_Green_Landscape_with_a_Beautiful_Swan_x0vpns?_a=BAMAOGUs0",
    "title": "Bright Green Landscape with a Beautiful Swan",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0018",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0019_Artistic_Flamingo_dal3pg",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--ckgFXCfW--/c_limit,w_1200/q_auto/f_auto/A0019_Artistic_Flamingo_dal3pg?_a=BAMAOGUs0",
    "title": "Artistic Flamingo",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0019",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0020_Vibrant_Peaceful_Swan_m0r4ke",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--cXBikGfO--/c_limit,w_1200/q_auto/f_auto/A0020_Vibrant_Peaceful_Swan_m0r4ke?_a=BAMAOGUs0",
    "title": "Vibrant Peaceful Swan",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0020",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0021_Autumn_Landscape_with_a_Running_Happy_Dog_hk2bwa",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--zLYHQzkX--/c_limit,w_1200/q_auto/f_auto/A0021_Autumn_Landscape_with_a_Running_Happy_Dog_hk2bwa?_a=BAMAOGUs0",
    "title": "Autumn Landscape with a Running Happy Dog",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0021",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0022_Full_Moon_Snowy_Landscape_axd9oj",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--4sAvjkK1--/c_limit,w_1200/q_auto/f_auto/A0022_Full_Moon_Snowy_Landscape_axd9oj?_a=BAMAOGUs0",
    "title": "Full Moon Snowy Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0022",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0023_Snowy_Landscape_1_e0rul8",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--9R1AEEnp--/c_limit,w_1200/q_auto/f_auto/A0023_Snowy_Landscape_1_e0rul8?_a=BAMAOGUs0",
    "title": "Snowy Landscape 1",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0023",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0024_Snowy_Landscape_2_pfnttq",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--HeWzV2ju--/c_limit,w_1200/q_auto/f_auto/A0024_Snowy_Landscape_2_pfnttq?_a=BAMAOGUs0",
    "title": "Snowy Landscape 2",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0024",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0025_Snowy_Waterfall_Landscape_xpp3dy",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--bZldfgIH--/c_limit,w_1200/q_auto/f_auto/A0025_Snowy_Waterfall_Landscape_xpp3dy?_a=BAMAOGUs0",
    "title": "Snowy Waterfall Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0025",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0026_Snowy_Autumn_Landscape_gi57gn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--0O7SwP7T--/c_limit,w_1200/q_auto/f_auto/A0026_Snowy_Autumn_Landscape_gi57gn?_a=BAMAOGUs0",
    "title": "Snowy Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0026",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0027_Snowy_Full_Moon_Autumn_Landscape_xensc4",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--n1OmjWEh--/c_limit,w_1200/q_auto/f_auto/A0027_Snowy_Full_Moon_Autumn_Landscape_xensc4?_a=BAMAOGUs0",
    "title": "Snowy Full Moon Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0027",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0028_Pink_Water_Lily_aums8g",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--xAm6dhZS--/c_limit,w_1200/q_auto/f_auto/A0028_Pink_Water_Lily_aums8g?_a=BAMAOGUs0",
    "title": "Pink Water Lily",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0028",
    "year": 2024,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0029_The_Strawberry_wiuoic",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--om5IXElk--/c_limit,w_1200/q_auto/f_auto/A0029_The_Strawberry_wiuoic?_a=BAMAOGUs0",
    "title": "The Strawberry",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0029",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0030_The_Donut_nrdkab",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--RR-XRqaY--/c_limit,w_1200/q_auto/f_auto/A0030_The_Donut_nrdkab?_a=BAMAOGUs0",
    "title": "The Donut",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0030",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0031_The_Fortune_Cookie_agybql",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--hRZDtcJ6--/c_limit,w_1200/q_auto/f_auto/A0031_The_Fortune_Cookie_agybql?_a=BAMAOGUs0",
    "title": "The Fortune Cookie",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0031",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0032_The_Pretzel_gijzya",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--8pufNsfS--/c_limit,w_1200/q_auto/f_auto/A0032_The_Pretzel_gijzya?_a=BAMAOGUs0",
    "title": "The Pretzel",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0032",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0033_The_Popsicle_kncdbb",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--dMND4iZY--/c_limit,w_1200/q_auto/f_auto/A0033_The_Popsicle_kncdbb?_a=BAMAOGUs0",
    "title": "The Popsicle",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0033",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0034_The_Coffee_Cup_ygfekk",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--_GvlYSEP--/c_limit,w_1200/q_auto/f_auto/A0034_The_Coffee_Cup_ygfekk?_a=BAMAOGUs0",
    "title": "The Coffee Cup",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0034",
    "year": 2026,
    "size": "10 x 12 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0035_The_Sliced_Oranges_ktbump",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--kJZmL63k--/c_limit,w_1200/q_auto/f_auto/A0035_The_Sliced_Oranges_ktbump?_a=BAMAOGUs0",
    "title": "The Sliced Oranges",
    "category": "Still Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0035",
    "year": 2026,
    "size": "10 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0036_The_High_Heels_f59rkl",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--pwCHYbXL--/c_limit,w_1200/q_auto/f_auto/A0036_The_High_Heels_f59rkl?_a=BAMAOGUs0",
    "title": "The High Heels",
    "category": "Still Paintings",
    "price": 999,
    "originalPrice": 1499,
    "sku": "SKU# A0036",
    "year": 2026,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0037_Pink_Tulip_yw8df5",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--KR3TjUB9--/c_limit,w_1200/q_auto/f_auto/A0037_Pink_Tulip_yw8df5?_a=BAMAOGUs0",
    "title": "Pink Tulip",
    "category": "Floral Paintings",
    "price": 1099,
    "originalPrice": 1699,
    "sku": "SKU# A0037",
    "year": 2026,
    "size": "10 x 10 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas",
    "isSold": false
  },
  {
    "public_id": "A0038_Cone_Flower_t8fnje",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--ddM7p8kY--/c_limit,w_1200/q_auto/f_auto/A0038_Cone_Flower_t8fnje?_a=BAMAOGUs0",
    "title": "Cone Flower",
    "category": "Floral Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0038",
    "year": 2026,
    "size": "10 x 10 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas",
    "isSold": false
  },
  {
    "public_id": "A0039_White_Lily_tohvti",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--qQbRaTHo--/c_limit,w_1200/q_auto/f_auto/A0039_White_Lily_tohvti?_a=BAMAOGUs0",
    "title": "White Lily",
    "category": "Floral Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0039",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas",
    "isSold": false
  },
  {
    "public_id": "A0040_The_Red_Dahlia_puimyq",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--lNXRLV6i--/c_limit,w_1200/q_auto/f_auto/A0040_The_Red_Dahlia_puimyq?_a=BAMAOGUs0",
    "title": "The Red Dahlia",
    "category": "Floral Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0040",
    "year": 2026,
    "size": "12 x 12 inches",
    "description": "Acrylic on Canvas (Framed)",
    "medium": "Acrylic on Canvas",
    "isSold": false
  },
  {
    "public_id": "A0041_Zinnia_Floral_Painting_tiemlp",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--ZLnlZrSr--/c_limit,w_1200/q_auto/f_auto/A0041_Zinnia_Floral_Painting_tiemlp?_a=BAMAOGUs0",
    "title": "Zinnia Floral Painting",
    "category": "Floral Paintings",
    "price": 1099,
    "originalPrice": 1699,
    "sku": "SKU# A0041",
    "year": 2026,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0041_The_Lady_with_a_Hat_Abstract_lsopgv",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--tKggpmQS--/c_limit,w_1200/q_auto/f_auto/A0041_The_Lady_with_a_Hat_Abstract_lsopgv?_a=BAMAOGUs0",
    "title": "The Lady with a Hat (Abstract)",
    "category": "Abstract Paintings",
    "price": 1099,
    "originalPrice": 1699,
    "sku": "SKU# A0042",
    "year": 2025,
    "size": "10 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0043_Serene_Buddha.heic_nvxg8g",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--RMbp9JFZ--/c_limit,w_1200/q_auto/f_auto/A0043_Serene_Buddha.heic_nvxg8g?_a=BAMAOGUs0",
    "title": "Serene Buddha",
    "category": "Spiritual Paintings",
    "price": 4999,
    "originalPrice": 6999,
    "sku": "SKU# A0043",
    "year": 2026,
    "size": "16 x 24 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0044_Krishna_with_Flute_apxkjx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--TSR0914W--/c_limit,w_1200/q_auto/f_auto/A0044_Krishna_with_Flute_apxkjx?_a=BAMAOGUs0",
    "title": "Krishna with Flute",
    "category": "Spiritual Paintings",
    "price": 6999,
    "originalPrice": 9999,
    "sku": "SKU# A0044",
    "year": 2026,
    "size": "24 x 33 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0045_Golden_Sun_Landscape_a8hzsx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Sucg6XYv--/c_limit,w_1200/q_auto/f_auto/A0045_Golden_Sun_Landscape_a8hzsx?_a=BAMAOGUs0",
    "title": "Golden Sun Landscape",
    "category": "Landscape Paintings",
    "price": 4999,
    "originalPrice": 6999,
    "sku": "SKU# A0045",
    "year": 2026,
    "size": "18 x 28 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0046_An_Abstract_Textured_Painting_rpeel0",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--tj2AWtok--/c_limit,w_1200/q_auto/f_auto/A0046_An_Abstract_Textured_Painting_rpeel0?_a=BAMAOGUs0",
    "title": "An Abstract Textured Painting",
    "category": "Abstract Paintings",
    "price": 2999,
    "originalPrice": 4999,
    "sku": "SKU# A0046",
    "year": 2026,
    "size": "18 x 18 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0047_The_Pyramids_of_Egypt_zh0ceg",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--zhf7cgLt--/c_limit,w_1200/q_auto/f_auto/A0047_The_Pyramids_of_Egypt_zh0ceg?_a=BAMAOGUs0",
    "title": "The Pyramids of Egypt",
    "category": "Landscape Paintings",
    "price": 2499,
    "originalPrice": 3999,
    "sku": "SKU# A0047",
    "year": 2026,
    "size": "12 x 16 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0048_The_Tree_Lined_Street_Painting_tmnzwt",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Yg0hdeFJ--/c_limit,w_1200/q_auto/f_auto/A0048_The_Tree_Lined_Street_Painting_tmnzwt?_a=BAMAOGUs0",
    "title": "The Tree Lined Street Painting",
    "category": "Landscape Paintings",
    "price": 4999,
    "originalPrice": 6999,
    "sku": "SKU# A0048",
    "year": 2026,
    "size": "18 x 24 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0049_The_Tree_Perspective_Painting_p0xwls",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Uo-9V5Gf--/c_limit,w_1200/q_auto/f_auto/A0049_The_Tree_Perspective_Painting_p0xwls?_a=BAMAOGUs0",
    "title": "The Tree Perspective Painting",
    "category": "Landscape Paintings",
    "price": 3999,
    "originalPrice": 5499,
    "sku": "SKU# A0049",
    "year": 2026,
    "size": "16 x 20 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0050_The_Sunflower_Painting_ec69vd",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--Q_5iu05i--/c_limit,w_1200/q_auto/f_auto/A0050_The_Sunflower_Painting_ec69vd?_a=BAMAOGUs0",
    "title": "The Sunflower Painting",
    "category": "Floral Paintings",
    "price": 6999,
    "originalPrice": 9999,
    "sku": "SKU# A0050",
    "year": 2026,
    "size": "24 inch Diameter",
    "description": "Acrylic on Stretched Round Canvas",
    "medium": "Acrylic on Stretched Round Canvas",
    "framed": false
  },
  {
    "public_id": "A0051_The_Spring_Lily_Painting_tjmqey",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--VwHtNajo--/c_limit,w_1200/q_auto/f_auto/A0051_The_Spring_Lily_Painting_tjmqey?_a=BAMAOGUs0",
    "title": "The Spring Lily Painting",
    "category": "Floral Paintings",
    "price": 6999,
    "originalPrice": 9999,
    "sku": "SKU# A0051",
    "year": 2026,
    "size": "24 inch Diameter",
    "description": "Acrylic on Stretched Round Canvas",
    "medium": "Acrylic on Stretched Round Canvas",
    "framed": false
  },
  {
    "public_id": "A0052_The_Ranunculus_Bouquete_gofc69",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--rf1C1L93--/c_limit,w_1200/q_auto/f_auto/A0052_The_Ranunculus_Bouquete_gofc69?_a=BAMAOGUs0",
    "title": "The Ranunculus Bouquete",
    "category": "Landscape Paintings",
    "price": 6999,
    "originalPrice": 9999,
    "sku": "SKU# A0052",
    "year": 2026,
    "size": "30 x 30 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0053_Vibrant_Tree_Painting_1_papeds",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--BP1HFUdl--/c_limit,w_1200/q_auto/f_auto/A0053_Vibrant_Tree_Painting_1_papeds?_a=BAMAOGUs0",
    "title": "Vibrant Tree Painting 1",
    "category": "Landscape Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0053",
    "year": 2026,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0054_Vibrant_Tree_Painting_2_tuqxy5",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--azkOryhN--/c_limit,w_1200/q_auto/f_auto/A0054_Vibrant_Tree_Painting_2_tuqxy5?_a=BAMAOGUs0",
    "title": "Vibrant Tree Painting 2",
    "category": "Landscape Paintings",
    "price": 1299,
    "originalPrice": 1899,
    "sku": "SKU# A0054",
    "year": 2026,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0055_Frozen_Waterfall_gvbzyn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--BG8I1TU2--/c_limit,w_1200/q_auto/f_auto/A0055_Frozen_Waterfall_gvbzyn?_a=BAMAOGUs0",
    "title": "Frozen Waterfall",
    "category": "Landscape Paintings",
    "price": 1099,
    "originalPrice": 1699,
    "sku": "SKU# A0055",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0056_Forest_Landscape_aqjaxx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--iBxTfGJA--/c_limit,w_1200/q_auto/f_auto/A0056_Forest_Landscape_aqjaxx?_a=BAMAOGUs0",
    "title": "Forest Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0056",
    "year": 2025,
    "size": "8 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0057_Antelope_Looking_at_You_zqcsge",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--MXXROuCG--/c_limit,w_1200/q_auto/f_auto/A0057_Antelope_Looking_at_You_zqcsge?_a=BAMAOGUs0",
    "title": "Antelope Looking at You",
    "category": "Animal Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0057",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0058_Autumn_Landscape_jts79a",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--fYEXlQ48--/c_limit,w_1200/q_auto/f_auto/A0058_Autumn_Landscape_jts79a?_a=BAMAOGUs0",
    "title": "Autumn Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0058",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0059_Autumn_Orange_Tree_bt2fgn",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--CKanEFKf--/c_limit,w_1200/q_auto/f_auto/A0059_Autumn_Orange_Tree_bt2fgn?_a=BAMAOGUs0",
    "title": "Autumn Orange Tree",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0059",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0060_Autumn_Trees_Lines_ji5umh",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--H3Hlmw5i--/c_limit,w_1200/q_auto/f_auto/A0060_Autumn_Trees_Lines_ji5umh?_a=BAMAOGUs0",
    "title": "Autumn Trees Lines",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0060",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0061_Beautiful_Sunset_Landscape_ohuhrv",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--9qUuuYsP--/c_limit,w_1200/q_auto/f_auto/A0061_Beautiful_Sunset_Landscape_ohuhrv?_a=BAMAOGUs0",
    "title": "Beautiful Sunset Landscape",
    "category": "Landscape Paintings",
    "price": 1299,
    "originalPrice": 1999,
    "sku": "SKU# A0061",
    "year": 2025,
    "size": "12 x 10 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0062_Lakeview_Landscape_o9v5ai",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--4Y-DU_H6--/c_limit,w_1200/q_auto/f_auto/A0062_Lakeview_Landscape_o9v5ai?_a=BAMAOGUs0",
    "title": "Lakeview Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0062",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0063_Landscape_Sunrise_jccqpz",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--LllaW1Ml--/c_limit,w_1200/q_auto/f_auto/A0063_Landscape_Sunrise_jccqpz?_a=BAMAOGUs0",
    "title": "Landscape Sunrise",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0063",
    "year": 2024,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0064_Snowfall_Landscape_lt0lxx",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--SSd_9rBd--/c_limit,w_1200/q_auto/f_auto/A0064_Snowfall_Landscape_lt0lxx?_a=BAMAOGUs0",
    "title": "Snowfall Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0064",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0065_Tulips_in_Sunset_oq6hgq",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--QV5bXcMl--/c_limit,w_1200/q_auto/f_auto/A0065_Tulips_in_Sunset_oq6hgq?_a=BAMAOGUs0",
    "title": "Tulips in Sunset",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1399,
    "sku": "SKU# A0065",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0066_Penguin_in_Snowfall_vdyfrk",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--yZ3dELye--/c_limit,w_1200/q_auto/f_auto/A0066_Penguin_in_Snowfall_vdyfrk?_a=BAMAOGUs0",
    "title": "Penguin in Snowfall",
    "category": "Animal Paintings",
    "price": 999,
    "originalPrice": 1399,
    "sku": "SKU# A0066",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0067_Christmas_Ornaments_mqaosc",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--cHgU53zT--/c_limit,w_1200/q_auto/f_auto/A0067_Christmas_Ornaments_mqaosc?_a=BAMAOGUs0",
    "title": "Christmas Ornaments",
    "category": "Festive Paintings",
    "price": 999,
    "originalPrice": 1399,
    "sku": "SKU# A0067",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0068_Lady_Watching_Sunset_hkmfjk",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--SrE4b691--/c_limit,w_1200/q_auto/f_auto/A0068_Lady_Watching_Sunset_hkmfjk?_a=BAMAOGUs0",
    "title": "Lady Watching Sunset",
    "category": "Figurative Paintings",
    "price": 999,
    "originalPrice": 1399,
    "sku": "SKU# A0068",
    "year": 2025,
    "size": "8 x 6 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0069_Lady_Watching_Sunrise_uqkyuo",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--MPOWUVA2--/c_limit,w_1200/q_auto/f_auto/A0069_Lady_Watching_Sunrise_uqkyuo?_a=BAMAOGUs0",
    "title": "Lady Watching Sunrise",
    "category": "Figurative Paintings",
    "price": 1299,
    "originalPrice": 1999,
    "sku": "SKU# A0069",
    "year": 2025,
    "size": "12 x 12 inches",
    "description": "Acrylic on Stretched Canvas",
    "medium": "Acrylic on Stretched Canvas",
    "framed": false
  },
  {
    "public_id": "A0070_Birdy_in_Snowfall_f8pjzd",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--QW01QUQ---/c_limit,w_1200/q_auto/f_auto/A0070_Birdy_in_Snowfall_f8pjzd?_a=BAMAOGUs0",
    "title": "Birdy in Snowfall",
    "category": "Animal Paintings",
    "price": 999,
    "originalPrice": 1699,
    "sku": "SKU# A0070",
    "year": 2025,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0071_Northern_Lights_htyprc",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--alaNJkFR--/c_limit,w_1200/q_auto/f_auto/A0071_Northern_Lights_htyprc?_a=BAMAOGUs0",
    "title": "Northern Lights",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0071",
    "year": 2024,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0072_Snowy_Landscape_3_zyx70i",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--6uCAHwV5--/c_limit,w_1200/q_auto/f_auto/A0072_Snowy_Landscape_3_zyx70i?_a=BAMAOGUs0",
    "title": "Snowy Landscape 3",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0072",
    "year": 2024,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "A0073_Snowy_Sunset_Landscape_h9q39x",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/s--o2d20X8S--/c_limit,w_1200/q_auto/f_auto/A0073_Snowy_Sunset_Landscape_h9q39x?_a=BAMAOGUs0",
    "title": "Snowy Sunset Landscape",
    "category": "Landscape Paintings",
    "price": 899,
    "originalPrice": 1499,
    "sku": "SKU# A0073",
    "year": 2024,
    "size": "8 x 8 inches",
    "description": "Acrylic on Canvas Board (Framed)",
    "medium": "Acrylic on Canvas Board",
    "isSold": false
  },
  {
    "public_id": "Budha in nature",
    "url": "https://res.cloudinary.com/dllpxron7/image/upload/v1772211569/IMG-20260227-WA0006_zxcfkj.jpg",
    "title": "Budha in nature",
    "category": "Acrylic",
    "price": 2999,
    "originalPrice": 3999,
    "sku": "SKU# B001",
    "year": 2026,
    "size": "12 x 16 inches",
    "description": "Beautiful Buddha painting in natural setting",
    "medium": "Acrylic on Canvas",
    "framed": false
  }
];

// Direct fetch - no cache
export const fetchImages = async () => {
  return IMAGES;
};